# Generated by Django 3.2.2 on 2021-05-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_about_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='option',
        ),
        migrations.AddField(
            model_name='about',
            name='option',
            field=models.ManyToManyField(related_name='optionabout', to='website.OptionAbout', verbose_name='option_about'),
        ),
    ]
