# Generated by Django 3.2.2 on 2021-05-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210517_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionabout',
            name='description',
        ),
        migrations.AddField(
            model_name='optionabout',
            name='option',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
