# Generated by Django 3.2.2 on 2021-05-17 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210517_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionabout',
            old_name='option',
            new_name='name',
        ),
    ]
