# Generated by Django 3.2 on 2021-05-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_option_optionabout_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='description_saison',
            new_name='description_contact',
        ),
        migrations.AddField(
            model_name='website',
            name='description_service',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
