# Generated by Django 3.2 on 2021-05-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210518_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='title_about',
        ),
        migrations.RemoveField(
            model_name='website',
            name='title_blog',
        ),
        migrations.RemoveField(
            model_name='website',
            name='title_saison',
        ),
        migrations.RemoveField(
            model_name='website',
            name='title_service',
        ),
        migrations.RemoveField(
            model_name='website',
            name='title_testimonial',
        ),
    ]
