# Generated by Django 3.2 on 2021-05-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210518_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='lien',
            field=models.URLField(default='https://vimeo.com/45830194'),
            preserve_default=False,
        ),
    ]
