# Generated by Django 3.2 on 2021-05-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_contact_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='galery',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.FileField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
